version: 1.0
provider:
  name: openfaas
functions:
  openfaas-imagecrawler:
    lang: dockerfile
    handler: ./openfaas-imagecrawler
    image: servernull/openfaas-imagecrawler:0.2.0
    environment:
      read_timeout: 120
      write_timeout: 120
      exec_timeout: 120

